
POST http://localhost:8080/table-value-source HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "RGE",
    "data": [
        {
            "period": {
                "month": 10,
                "year": 2024
            },
            "amount": 300.50
        }
    ]
}